version: '3.7'
services:
  web:
    ports:
        - "8000:80"
  db:
    ports:
        - "3306:3306"
    volumes:
        - /Users/takashi/Database/rare-piece-db:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 06041944
        MYSQL_DATABASE: rare_piece_db
        MYSQL_USER: takashi
        MYSQL_PASSWORD: p@ssw0rd
